import React, { useState, useEffect, useMemo, useRef } from 'react';
import StarRating from '../components/StarRating';
import ExperienceSelection from '../components/ExperienceSelection';
import ReviewDraft from '../components/ReviewDraft';
import { generateReview } from '../services/reviewGenerator';
import { getBusinessBySlug, getStoredCustomBusinesses } from '../data/businesses';

const TYPE_EMOJI_MAP = {
  'waffle shop': '🧇',
  'cafe': '☕',
  'grocery store': '🛒',
  'cocktail bar': '🍸',
  'restaurant': '🍽️',
  'bar': '🍻'
};

/**
 * Attempt to build a business object directly from URL query params.
 * This is the primary source when a QR is scanned on a fresh phone.
 * Expected params: ?name=Royal%20Cafe&google=<encoded-google-url>
 */
function businessFromUrl() {
  if (typeof window === 'undefined') return null;
  const params = new URLSearchParams(window.location.search);
  const name = params.get('name');
  const google = params.get('google');
  if (!name || !google) return null;
  return {
    name,
    googleReviewUrl: google,
    // type is not encoded in the URL; omit it (page still renders fine without it)
    type: null,
  };
}

export default function CustomerReviewPage({ slug }) {
  // 1. URL params — set when QR is scanned (works on any phone, no localStorage needed)
  const urlBusiness = useMemo(() => businessFromUrl(), []);

  // 2. localStorage / preset fallback
  const localBiz = useMemo(
    () => (urlBusiness ? null : getBusinessBySlug(slug)),
    [slug, urlBusiness]
  );

  const [business, setBusiness] = useState(urlBusiness || localBiz);
  const [loading, setLoading] = useState(!urlBusiness && !localBiz);
  const [error, setError] = useState(null);

  const [rating, setRating] = useState(0);
  const [selectedAspects, setSelectedAspects] = useState([]);
  const [specificFeedback, setSpecificFeedback] = useState('');
  const [userEditedReview, setUserEditedReview] = useState(null);

  const experienceRef = useRef(null);

  // Sync with backend API to catch any runtime configuration updates
  useEffect(() => {
    // Reset review-interaction state when navigating to a different business
    setRating(0);
    setSelectedAspects([]);
    setSpecificFeedback('');
    setUserEditedReview(null);

    // URL params are the authoritative source — no network call needed
    const fromUrl = businessFromUrl();
    if (fromUrl) {
      setBusiness(fromUrl);
      setLoading(false);
      setError(null);
      return;
    }

    // Fallback: localStorage / preset
    const found = getBusinessBySlug(slug);
    setBusiness(found);
    setLoading(!found);
    setError(null);

    async function fetchLatestBusiness() {
      // If business was created/customized in localStorage, prioritize it
      const custom = getStoredCustomBusinesses();
      if (custom[slug.toLowerCase()]) {
        setLoading(false);
        return;
      }

      try {
        const res = await fetch(`/api/businesses/${slug}`);
        if (!res.ok) {
          if (!found) {
            throw new Error(res.status === 404 ? 'Business not found' : 'Failed to load business');
          }
          return;
        }
        const data = await res.json();
        if (data.success && data.data) {
          setBusiness(data.data);
        }
      } catch (err) {
        if (!found) {
          setError(err.message);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchLatestBusiness();
  }, [slug]);

  // Compute the deterministic review draft
  const autoGeneratedReview = useMemo(() => {
    if (!business || rating === 0) return '';
    return generateReview({
      businessName: business.name,
      rating,
      likedAspects: selectedAspects,
      specificFeedback
    });
  }, [business, rating, selectedAspects, specificFeedback]);

  // If user has not typed manual edits, use the auto-generated one
  const currentReviewText = userEditedReview !== null ? userEditedReview : autoGeneratedReview;

  const handleRatingSelect = (newRating) => {
    setRating(newRating);
    setUserEditedReview(null);

    setTimeout(() => {
      if (experienceRef.current) {
        experienceRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 120);
  };

  const handleToggleAspect = (aspectId) => {
    setUserEditedReview(null);
    setSelectedAspects((prev) =>
      prev.includes(aspectId) ? prev.filter((item) => item !== aspectId) : [...prev, aspectId]
    );
  };

  const handleFeedbackChange = (text) => {
    setUserEditedReview(null);
    setSpecificFeedback(text);
  };

  const handleManualReviewEdit = (text) => {
    setUserEditedReview(text);
  };

  const handleResetToAuto = () => {
    setUserEditedReview(null);
  };

  if (loading) {
    return (
      <div className="mobile-canvas flex-center">
        <div className="loader-spinner" />
        <p className="loading-text">Loading...</p>
      </div>
    );
  }

  if (error || !business) {
    return (
      <div className="mobile-canvas flex-center error-page">
        <div className="error-icon">⚠️</div>
        <h2>Business Not Found</h2>
        <p>We couldn't locate a business for <code>/r/{slug}</code>.</p>
        <a href="/" className="btn btn-secondary">Go to Developer Portal</a>
      </div>
    );
  }

  const avatar = TYPE_EMOJI_MAP[business.type?.toLowerCase()] || '🏪';

  return (
    <div className="mobile-wrapper">
      <main className="mobile-canvas">
        {/* Reusable Header */}
        <header className="shop-header">
          <div className="shop-avatar">
            <span>{avatar}</span>
          </div>
          <h1 className="shop-name">{business.name}</h1>
          {business.type && (
            <span className="business-type-pill">{business.type}</span>
          )}
        </header>

        {/* 1. Star Rating Selection */}
        <section className="step-card">
          <StarRating
            rating={rating}
            onRatingChange={handleRatingSelect}
            businessName={business.name}
          />
        </section>

        {/* 2. Experience Selection (Appears once rating is tapped) */}
        {rating > 0 && (
          <div ref={experienceRef} className="step-section">
            <section className="step-card">
              <ExperienceSelection
                selectedAspects={selectedAspects}
                onToggleAspect={handleToggleAspect}
                specificFeedback={specificFeedback}
                onFeedbackChange={handleFeedbackChange}
                rating={rating}
              />
            </section>

            {/* 3. Review Draft Generation & Actions */}
            <section className="step-card">
              <ReviewDraft
                reviewText={currentReviewText}
                onReviewChange={handleManualReviewEdit}
                googleReviewUrl={business.googleReviewUrl}
                rating={rating}
              />
              {userEditedReview !== null && (
                <div className="reset-draft-container">
                  <button
                    type="button"
                    onClick={handleResetToAuto}
                    className="btn-reset-draft"
                  >
                    ↺ Reset to auto-generated draft
                  </button>
                </div>
              )}
            </section>
          </div>
        )}

        {/* Minimal footer */}
        <footer className="page-footer">
          <p className="footer-note">
            Fast, genuine reviews powered by direct customer feedback.
          </p>
        </footer>
      </main>
    </div>
  );
}
