import React, { useState, useEffect, useMemo, useRef } from 'react';
import StarRating from '../components/StarRating';
import ExperienceSelection from '../components/ExperienceSelection';
import ReviewDraft from '../components/ReviewDraft';
import { generateReview } from '../services/reviewGenerator';

export default function CustomerReviewPage({ slug, businessData, onRefreshBusiness }) {
  const [rating, setRating] = useState(0);
  const [selectedAspects, setSelectedAspects] = useState([]);
  const [specificFeedback, setSpecificFeedback] = useState('');
  const [userEditedReview, setUserEditedReview] = useState(null);
  const [loading, setLoading] = useState(!businessData);
  const [error, setError] = useState(null);
  const [business, setBusiness] = useState(businessData);

  const experienceRef = useRef(null);

  // Fetch business info if not passed down directly
  useEffect(() => {
    if (businessData) {
      setBusiness(businessData);
      setLoading(false);
      return;
    }

    async function fetchBusiness() {
      try {
        setLoading(true);
        setError(null);
        const res = await fetch(`/api/businesses/${slug}`);
        if (!res.ok) {
          throw new Error(res.status === 404 ? 'Business not found' : 'Failed to load business');
        }
        const data = await res.json();
        if (data.success && data.data) {
          setBusiness(data.data);
        } else {
          throw new Error('Invalid response from server');
        }
      } catch (err) {
        // Fallback for standalone demo if backend is offline
        if (slug === 'demo-waffle-shop') {
          setBusiness({
            name: 'Demo Waffle Shop',
            slug: 'demo-waffle-shop',
            googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
            avatarEmoji: '🧇'
          });
        } else {
          setError(err.message);
        }
      } finally {
        setLoading(false);
      }
    }

    fetchBusiness();
  }, [slug, businessData]);

  // Compute the deterministic review draft
  const autoGeneratedReview = useMemo(() => {
    if (!business || rating === 0) return '';
    return generateReview({
      businessName: business.name,
      rating,
      likedAspects: selectedAspects,
      specificFeedback
    });
  }, [business, rating, selectedAspects, specificFeedback]);

  // If user has not typed their own manual edits in the draft box, use the generated one
  const currentReviewText = userEditedReview !== null ? userEditedReview : autoGeneratedReview;

  const handleRatingSelect = (newRating) => {
    setRating(newRating);
    setUserEditedReview(null); // Reset manual edits when rating shifts

    // Smooth scroll down to experience selection on mobile
    setTimeout(() => {
      if (experienceRef.current) {
        experienceRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    }, 120);
  };

  const handleToggleAspect = (aspectId) => {
    setUserEditedReview(null);
    setSelectedAspects((prev) =>
      prev.includes(aspectId) ? prev.filter((item) => item !== aspectId) : [...prev, aspectId]
    );
  };

  const handleFeedbackChange = (text) => {
    setUserEditedReview(null);
    setSpecificFeedback(text);
  };

  const handleManualReviewEdit = (text) => {
    setUserEditedReview(text);
  };

  const handleResetToAuto = () => {
    setUserEditedReview(null);
  };

  if (loading) {
    return (
      <div className="mobile-canvas flex-center">
        <div className="loader-spinner" />
        <p className="loading-text">Loading...</p>
      </div>
    );
  }

  if (error || !business) {
    return (
      <div className="mobile-canvas flex-center error-page">
        <div className="error-icon">⚠️</div>
        <h2>Business Not Found</h2>
        <p>We couldn't locate a business at <code>/r/{slug}</code>.</p>
        <a href="/" className="btn btn-secondary">Go to Home</a>
      </div>
    );
  }

  return (
    <div className="mobile-wrapper">
      <main className="mobile-canvas">
        {/* Minimal Header */}
        <header className="shop-header">
          <div className="shop-avatar">
            <span>{business.avatarEmoji || '🧇'}</span>
          </div>
          <h1 className="shop-name">{business.name}</h1>
          <span className="verified-badge">Verified Review Flow</span>
        </header>

        {/* 1. Star Rating Selection */}
        <section className="step-card">
          <StarRating
            rating={rating}
            onRatingChange={handleRatingSelect}
            businessName={business.name}
          />
        </section>

        {/* 2. Experience Selection (Appears once rating is tapped) */}
        {rating > 0 && (
          <div ref={experienceRef} className="step-section">
            <section className="step-card">
              <ExperienceSelection
                selectedAspects={selectedAspects}
                onToggleAspect={handleToggleAspect}
                specificFeedback={specificFeedback}
                onFeedbackChange={handleFeedbackChange}
                rating={rating}
              />
            </section>

            {/* 3. Review Draft Generation & Actions */}
            <section className="step-card">
              <ReviewDraft
                reviewText={currentReviewText}
                onReviewChange={handleManualReviewEdit}
                googleReviewUrl={business.googleReviewUrl}
                rating={rating}
              />
              {userEditedReview !== null && (
                <div className="reset-draft-container">
                  <button
                    type="button"
                    onClick={handleResetToAuto}
                    className="btn-reset-draft"
                  >
                    ↺ Reset to auto-generated draft
                  </button>
                </div>
              )}
            </section>
          </div>
        )}

        {/* Minimal footer branding */}
        <footer className="page-footer">
          <p className="footer-note">
            Fast, genuine reviews powered by direct customer feedback.
          </p>
        </footer>
      </main>
    </div>
  );
}
